Review README
jf87/SM3-Text-to-Query pull request #1
Opened 2024-11-14 10:43 UTC by cedricosei

This update contains an initial review of the README files, which describe the main and subdirectories. In addition it contains a small adjustment in the license file (adding of year and names).

2024-11-14 11:01 UTC, jf87 commented on data/README.md
Please check that the paths are correct. The first two ones are already not correct

2024-11-14 11:03 UTC, jf87 commented
Now the overall README and the data and src README.md files contain duplicated info. Please fix.

2024-11-14 12:19 UTC, jf87 commented on data/README.md
> +- `./synthea_database` contains the Synthea data used as the basis for PostgreSQL, Graph DB (RDF), Neo4j, and MongoDB.
The paths are still wrong. Please check all things carefully before submitting it...

2024-11-14 14:24 UTC, cedricosei commented
I updated the paths and changed the project README slightly such that we don't have the duplicate definition as mentioned above. I made sure to double check it more thoroughly this time.

2024-11-14 17:05 UTC, jf87 commented on README.md
> +The `./data` directory contains various used templates, synthea data, train and dev data and the compoted results.
Fix to:
The `./data` directory contains our template questions, the Synthea data, train and dev data, and the Text-to-Query results of our evaluated LLMs for all databases.

2024-11-14 17:06 UTC, jf87 commented on README.md
> +The `./src` directory contains the code to reproduce the results presented in SM3-Text-to-Query research.
The `./src` directory contains the code to reproduce the results presented in SM3-Text-to-Query.

2024-11-14 17:08 UTC, jf87 requested changes
see comments

2024-11-14 20:23 UTC, cedricosei commented
Change requests were implemented as described in the comments above.

2024-11-15 10:01 UTC, jf87 approved these changes
Looks good. Thanks!

2024-11-15 10:01 UTC, merged